project:
  type: website

website:
  title: "Data Science Workflows with Posit Tools - R Focus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



